# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 18002
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    # 它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
    worker-threads: 64
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

spring:
  application:
    name: yurun-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
      discovery:
        locator:
          enabled: true
      routes:
#        - id: report-kg-service
#          uri: lb://report-kg-service
#          predicates:
#            - Path=/report-kg/**
#          filters:
#            - StripPrefix=1
#        - id: report-middle-service
#          uri: lb://report-middle-service
#          predicates:
#            - Path=/report-middle/**
#          filters:
#            - StripPrefix=1
#        - id: report-sp-service
#          uri: lb://report-sp-service
#          predicates:
#            - Path=/report-nc/**
#          filters:
#            - StripPrefix=1
#        - id: sap-service
#          uri: lb://sap-service
#          predicates:
#            - Path=/report-sp/**
#          filters:
#            - StripPrefix=1
#        - id: common-service
#          uri: lb://common-service
#          predicates:
#            - Path=/common/**
#          filters:
#            - StripPrefix=1
#        - id: qa-service
#          uri: lb://qa-service
#          predicates:
#            - Path=/qa/**
#          filters:
#            - StripPrefix=1
#        - id: message-service
#          uri: lb://message-service
#          predicates:
#            - Path=/message/**
#          filters:
#            - StripPrefix=1
#        - id: visitor-service
#          uri: lb://visitor-service
#          predicates:
#            - Path=/visitor/**
#          filters:
#            - StripPrefix=1
#        - id: track-service
#          uri: lb://track-service
#          predicates:
#            - Path=/track/**
#          filters:
#            - StripPrefix=1

#超时配置
ribbon:
  # 设置连接超时时间
  ConnectTimeout: 600000
  # 设置读取超时时间
  ReadTimeout: 600000
  #重试
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
  threadpool:
    default:
      coreSize: 20
feign:
  client:
    config:
      default:
        connectTimeout: 200000
        readTimeout: 200000
        loggerLevel: basic
  hystrix:
    enabled: true
  httpclient:
    enabled: false

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

#jwt生成密钥
#jwt:
#  secret:
#    key: asdfghjkl

#不进行token拦截
#auth:
#  skip:
#    urls: /common/API120101,/common/API110101
#  ban:
#    urls: /visitor/HR100203,/visitor/HR120101,/visitor/HR120102,/visitor/HR120103
#  globel:
#    urls: /common/API100101
